# Translations template for nova_powervm.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the nova_powervm
# project.
# Automatically generated, 2015.
#
msgid ""
msgstr ""
"Project-Id-Version: nova_powervm 0.0.1.dev394\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-10-06 13:59-0500\n"
"PO-Revision-Date: 2015-10-06 13:59-0500\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.0\n"

#: nova_powervm/virt/powervm/driver.py:131
#, python-format
msgid "Expected exactly one host; found %d"
msgstr "Précisément un hôte attendu ; trouvé %d"

#: nova_powervm/virt/powervm/driver.py:695
#, python-format
msgid "Plug vif failed because instance %s was not found."
msgstr "Echec de connexion vif car l'instance %s est introuvable."

#: nova_powervm/virt/powervm/driver.py:700
msgid "Plug vif failed because of an unexpected error."
msgstr "Echec de connexion vif en raison d'une erreur inattendue."

#: nova_powervm/virt/powervm/driver.py:797
msgid "Cannot reduce disk size."
msgstr "Impossible de réduire la taille du disque."

#: nova_powervm/virt/powervm/exception.py:37
#, python-format
msgid ""
"Unable to locate the volume group %(vol_grp)s to store the virtual "
"optical media within.  Unable to create the media repository."
msgstr ""
"Impossible de localiser le groupe de volumes %(vol_grp)s dans lequel "
"stocker le support optique virtuel. Impossible de créer le référentiel "
"de supports. "

#: nova_powervm/virt/powervm/exception.py:44
#, python-format
msgid "Expected to find exactly one management partition; found %(count)d."
msgstr "Précisément une partition de gestion attendue ; trouvé %(count)d."

#: nova_powervm/virt/powervm/exception.py:50
#, python-format
msgid ""
"Having scanned SCSI bus %(bus)x on the management partition, disk with "
"UDID %(udid)s failed to appear after %(polls)d polls over %(timeout)d "
"seconds."
msgstr ""
"Après analyse du bus SCSI %(bus)x sur la partition de gestion, le disque "
"avec l'UDID %(udid)s n'est pas apparu après %(polls)d interrogations "
"sur %(timeout)d secondes."

#: nova_powervm/virt/powervm/exception.py:57
#, python-format
msgid ""
"Expected to find exactly one disk on the management partition at "
"%(path_pattern)s; found %(count)d."
msgstr ""
"Précisément un disque attendu sur la partition de gestion à l'adresse "
"%(path_pattern)s ; trouvé %(count)d."

#: nova_powervm/virt/powervm/exception.py:63
#, python-format
msgid ""
"Device %(devpath)s is still present on the management partition after "
"attempting to delete it.  Polled %(polls)d times over %(timeout)d "
"seconds."
msgstr ""
"L'unité %(devpath)s est encore présente sur la partition de gestion "
"après la tentative de suppression. %(polls)d interrogations sur %(timeout)d "
"secondes."

#: nova_powervm/virt/powervm/exception.py:69
#, python-format
msgid ""
"Failed to map boot disk of instance %(instance_name)s to the management "
"partition from any Virtual I/O Server."
msgstr ""
"Echec du mappage du disque d'amorçage de l'instance %(instance_name)s "
"sur la partition de gestion depuis tout serveur Virtual I/O Server."

#: nova_powervm/virt/powervm/exception.py:75
#, python-format
msgid ""
"Failed to find newly-created mapping of storage element %(stg_name)s from"
" Virtual I/O Server %(vios_name)s to the management partition."
msgstr ""
"Echec de détection du mappage nouvellement créé de l'élément de stockage "
"%(stg_name)s du serveur Virtual I/O Server %(vios_name)s à la partition "
"de gestion."

#: nova_powervm/virt/powervm/exception.py:81
#, python-format
msgid "Unable to locate the volume group '%(vg_name)s' for this operation."
msgstr "Impossible de localiser le groupe de volumes '%(vg_name)s' pour cette opération."

#: nova_powervm/virt/powervm/exception.py:86
#, python-format
msgid "Unable to locate the Cluster '%(clust_name)s' for this operation."
msgstr "Impossible de localiser la grappe '%(clust_name)s' pour cette opération."

#: nova_powervm/virt/powervm/exception.py:91
msgid "Unable to locate any Cluster for this operation."
msgstr "Impossible de localiser une grappe pour cette opération."

#: nova_powervm/virt/powervm/exception.py:95
#, python-format
msgid ""
"Unexpectedly found %(clust_count)d Clusters matching name "
"'%(clust_name)s'."
msgstr ""
"Détection inattendue de %(clust_count)d grappes avec un nom correspondant."
"avec le nom correspondant '%(clust_name)s'."

#: nova_powervm/virt/powervm/exception.py:100
#, python-format
msgid ""
"No cluster_name specified.  Refusing to select one of the %(clust_count)d"
" Clusters found."
msgstr ""
"Aucun cluster_name spécifié. Refus de sélectionner une des %(clust_count)d"
" grappes détectées."

#: nova_powervm/virt/powervm/exception.py:105
#, python-format
msgid ""
"Unable to attach storage (id: %(volume_id)s) to virtual machine "
"%(instance_name)s.  %(reason)s"
msgstr ""
"Impossible de connecter le stockage (ID : %(volume_id)s) à la machine "
"virtuelle %(instance_name)s. %(reason)s"

#: nova_powervm/virt/powervm/exception.py:110
#, python-format
msgid ""
"Unable to detach volume (id: %(volume_id)s) from virtual machine "
"%(instance_name)s.  %(reason)s"
msgstr ""
"Impossible de déconnecter le volume (ID : %(volume_id)s) de la machine "
"virtuelle %(instance_name)s. %(reason)s"

#: nova_powervm/virt/powervm/exception.py:115
#, python-format
msgid ""
"Unable to perform pre live migration steps on volume (id: %(volume_id)s) "
"from virtual machine %(instance_name)s."
msgstr ""
"Impossible d'effectuer la procédure de pré-migration sur le volume "
"(ID : %(volume_id)s) depuis la machine virtuelle %(instance_name)s."

#: nova_powervm/virt/powervm/live_migration.py:37
#, python-format
msgid "Live migration of instance '%(name)s' failed for reason: %(reason)s"
msgstr "Echec de la migration active de l'instance '%(name)s' ; motif : %(reason)s"

#: nova_powervm/virt/powervm/live_migration.py:42
#, python-format
msgid ""
"Live migration of instance '%(name)s' failed because the migration state "
"is: %(state)s"
msgstr ""
"Echec de la migration active de l'instance '%(name)s' car l'état de "
"la migration est %(state)s"

#: nova_powervm/virt/powervm/live_migration.py:47
#, python-format
msgid ""
"Live migration of instance '%(name)s' failed because it is not ready. "
"Reason: %(reason)s"
msgstr ""
"Echec de la migration active de l'instance '%(name)s' car non prête. "
"Motif : %(reason)s"

#: nova_powervm/virt/powervm/live_migration.py:52
#, python-format
msgid ""
"Cannot migrate instance '%(name)s' because the memory region size of the "
"source (%(source_mrs)d MB) does not match the memory region size of the "
"target (%(target_mrs)d MB)."
msgstr ""
"Impossible de migrer l'instance '%(name)s' car la taille de région de "
"mémoire de la source (%(source_mrs)d Mo) ne correspond pas à celle de "
"la cible (%(target_mrs)d Mo)."

#: nova_powervm/virt/powervm/live_migration.py:59
#, python-format
msgid ""
"Cannot migrate %(name)s because its processor compatibility mode %(mode)s"
" is not in the list of modes \"%(modes)s\" supported by the target host."
msgstr ""
"Impossible de migrer %(name)s car son mode de compatibilité processeur "
"%(mode)s n'est pas dans la liste de modes \"%(modes)s\" pris en charge "
"par l'hôte cible."

#: nova_powervm/virt/powervm/live_migration.py:66
#, python-format
msgid ""
"Cannot migrate %(name)s because the host %(host)s only allows %(allowed)s"
" concurrent migrations and %(running)s migrations are currently running."
msgstr ""
"Impossible de migrer %(name)s car l'hôte %(host)s autorise seulement %(allowed)s"
" migrations simultanées et %(running)s migrations sont en cours."

#: nova_powervm/virt/powervm/live_migration.py:72
#, python-format
msgid ""
"Cannot migrate %(name)s because the volume %(volume)s cannot be attached "
"on the destination host %(host)s."
msgstr ""
"Impossible de migrer %(name)s car le volume %(volume)s ne peut pas être "
"connecté à l'hôte de destination %(host)s."

#: nova_powervm/virt/powervm/vm.py:343
#, python-format
msgid "Multiple Shared Processing Pools with name %(pool)s."
msgstr "Plusieurs pools de traitement partagé avec le nom %(pool)s."

#: nova_powervm/virt/powervm/vm.py:347
#, python-format
msgid "Unable to find Shared Processing Pool %(pool)s"
msgstr "Impossible de trouver le pool de traitement partagé %(pool)s"

#: nova_powervm/virt/powervm/vm.py:369
#, python-format
msgid ""
"Flavor attribute %(attr)s must be either True or False.  Current value "
"%(val)s is not allowed."
msgstr ""
"L'attribut de style %(attr)s doit être True ou False. La valeur en cours "
"%(val)s n'est pas admise."

#: nova_powervm/virt/powervm/tasks/network.py:39
msgid "Virtual interface unplug failed"
msgstr "Echec de déconnexion de l'interface virtuelle"

#: nova_powervm/virt/powervm/volume/vscsi.py:206
#, python-format
msgid ""
"Failed to discover valid hdisk on any Virtual I/O Server for volume "
"%(volume_id)s."
msgstr ""
"Echec de reconnaissance de hdisk valide sur un serveur Virtual I/O Server "
"pour le volume %(volume_id)s."

