# Translations template for nova_powervm.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the nova_powervm
# project.
# Automatically generated, 2015.
#
msgid ""
msgstr ""
"Project-Id-Version: nova_powervm 0.0.1.dev394\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-10-06 13:59-0500\n"
"PO-Revision-Date: 2015-10-06 13:59-0500\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.0\n"

#: nova_powervm/virt/powervm/driver.py:386
#: nova_powervm/virt/powervm/driver.py:396
msgid "VM was not found during destroy operation."
msgstr "La máquina virtual no se ha encontrado durante la operación de destrucción."

#: nova_powervm/virt/powervm/driver.py:742
#, python-format
msgid ""
"my_ip address (%(my_ip)s) was not found on any of the interfaces: "
"%(ifaces)s"
msgstr ""
"my_ip address (%(my_ip)s) no se ha encontrado en ninguna de las interfaces: "
"%(ifaces)s"

#: nova_powervm/virt/powervm/driver.py:1084
msgid "Rolling back live migration."
msgstr "Se está revirtiendo la migración en directo."

#: nova_powervm/virt/powervm/host.py:174
msgid ""
"Host CPU Metrics determined that the total cycles reported was less than "
"the used cycles.  This indicates an issue with the PCM data.  Please "
"investigate the results."
msgstr ""
"Las métricas de CPU del host han determinado que el número total de ciclos notificados es inferior al número "
"de ciclos utilizados. Esto indica un problema con los datos de PCM. "
"Examine los resultados."

#: nova_powervm/virt/powervm/media.py:299
#, python-format
msgid "Unable to read volume groups for Virtual I/O Server %s"
msgstr "No se pueden leer los grupos de volúmenes para el servidor de E/S virtual %s"

#: nova_powervm/virt/powervm/disk/driver.py:168
#, python-format
msgid ""
"Failed to map boot disk %(disk_name)s of instance %(instance_name)s to "
"the management partition from Virtual I/O Server %(vios_name)s: %(exc)s"
msgstr ""
"No se ha podido correlacionar el disco de arranque %(disk_name)s de la instancia %(instance_name)s con "
"la partición de gestión del servidor de E/S virtual %(vios_name)s: %(exc)s"

#: nova_powervm/virt/powervm/tasks/network.py:104
#, python-format
msgid ""
"Unable to unplug VIF with mac %(mac)s for instance %(inst)s.  The VIF was"
" not found on the instance."
msgstr ""
"No se puede desconectar VIF con mac %(mac)s para la instancia %(inst)s. El VIF no se ha"
" encontrado en la instancia."

#: nova_powervm/virt/powervm/tasks/storage.py:55
#, python-format
msgid "Volume %(vol)s for instance %(inst)s to be disconnected"
msgstr "Volumen %(vol)s para la instancia %(inst)s que se debe desconectar"

#: nova_powervm/virt/powervm/tasks/storage.py:71
#, python-format
msgid ""
"Unable to disconnect volume for %(inst)s during rollback.  Error was: "
"%(error)s"
msgstr ""
"No se ha podido desconectar el volumen para %(inst)s durante la reversión. El error fue: "
"%(error)s"

#: nova_powervm/virt/powervm/tasks/storage.py:98
#, python-format
msgid "Volume %(vol)s for instance %(inst)s to be re-connected"
msgstr "Volumen %(vol)s para la instancia %(inst)s que se debe volver a conectar"

#: nova_powervm/virt/powervm/tasks/storage.py:115
#, python-format
msgid ""
"Unable to re-connect volume for %(inst)s during rollback.  Error was: "
"%(error)s"
msgstr ""
"No se puede volver a conectar el volumen para %(inst)s durante la reversión. El error es: "
"%(error)s"

#: nova_powervm/virt/powervm/tasks/storage.py:156
#, python-format
msgid "Image for instance %s to be deleted"
msgstr "Imagen para la instancia %s que se debe suprimir"

#: nova_powervm/virt/powervm/tasks/storage.py:203
#, python-format
msgid "Disk image being disconnected from instance %s"
msgstr "Imagen de disco que se está desconectando de la instancia %s"

#: nova_powervm/virt/powervm/tasks/storage.py:274
#, python-format
msgid ""
"Unmapping boot disk %(disk_name)s of instance %(instance_name)s from "
"management partition via Virtual I/O Server %(vios_name)s."
msgstr ""
"Se está descorrelacionando el disco de arranque %(disk_name)s de la instancia %(instance_name)s de "
"la partición de gestión mediante el servidor de E/S virtual %(vios_name)s."

#: nova_powervm/virt/powervm/tasks/storage.py:286
#, python-format
msgid "Removing disk %(disk_path)s from the management partition."
msgstr "Se está eliminando el disco %(disk_path)s de la partición de gestión."

#: nova_powervm/virt/powervm/volume/npiv.py:170
#, python-format
msgid ""
"No storage connections found between the Virtual I/O Servers and FC "
"Fabric %(fabric)s. The connection might be removed already."
msgstr ""
"No se han encontrado conexiones de almacenamiento entre los servidores de E/S virtuales y el canal de fibra "
"Entramado %(fabric)s. Es posible que la conexión ya se haya eliminado."

#: nova_powervm/virt/powervm/volume/npiv.py:478
#, python-format
msgid ""
"No storage connections found between the Virtual I/O Servers and FC "
"Fabric %(fabric)s."
msgstr ""
"No se han encontrado conexiones de almacenamiento entre los servidores de E/S virtuales y el canal de fibra "
"Entramado %(fabric)s."

#: nova_powervm/virt/powervm/volume/npiv.py:564
#, python-format
msgid ""
"No NPIV mappings exist for instance %(inst)s on fabric %(fabric)s.  May "
"not have connected to the fabric yet or fabric configuration was recently"
" modified."
msgstr ""
"No existen correlaciones de NPIV para la instancia %(inst)s en el entramado %(fabric)s. Es posible que "
"aún no se hayan conectado con el entramado o que se haya modificado recientemente la configuración"
" del entramado."

#: nova_powervm/virt/powervm/volume/vscsi.py:148
#, python-format
msgid ""
"Discovered device %(dev)s for volume %(volume)s on %(vios)s is in use. "
"Error code: %(status)s."
msgstr ""
"El dispositivo descubierto %(dev)s para el volumen %(volume)s en %(vios)s está en uso. "
"Código de error: %(status)s."

#: nova_powervm/virt/powervm/volume/vscsi.py:237
#, python-format
msgid ""
"Disconnect Volume: No mapped device found on Virtual I/O Server %(vios)s "
"for volume %(volume_id)s.  Volume UDID: %(volume_uid)s"
msgstr ""
"Desconectar volumen: No se ha encontrado ningún dispositivo correlacionado en el servidor de E/S virtual %(vios)s "
"para el volumen %(volume_id)s. UDID de volumen: %(volume_uid)s"

#: nova_powervm/virt/powervm/volume/vscsi.py:246
#, python-format
msgid ""
"Disconnect Volume: Failed to find disk on Virtual I/O Server "
"%(vios_name)s for volume %(volume_id)s. Volume UDID: %(volume_uid)s.  "
"Error: %(error)s"
msgstr ""
"Desconectar volumen: No se ha encontrado el disco en el servidor de E/S virtual "
"%(vios_name)s para el volumen %(volume_id)s. UDID de volumen: %(volume_uid)s.  "
"Error: %(error)s"

#: nova_powervm/virt/powervm/volume/vscsi.py:288
#, python-format
msgid ""
"Disconnect Volume: Failed to disconnect the volume %(volume_id)s on ANY "
"of the Virtual I/O Servers for instance %(inst)s."
msgstr ""
"Desconectar volumen: No se ha podido desconectar el volumen %(volume_id)s en NINGUNO "
"de los servidores de E/S virtuales para la instancia %(inst)s."

#: nova_powervm/virt/powervm/volume/vscsi.py:318
#, python-format
msgid ""
"There was an error removing the hdisk %(disk)s from the Virtual I/O "
"Server."
msgstr ""
"Se ha producido un error al eliminar el hdisk %(disk)s del servidor de E/S "
"virtual."

