# Translations template for networking-powervm.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the networking-powervm
# project.
# Automatically generated, 2015.
#
msgid ""
msgstr ""
"Project-Id-Version: networking-powervm 0.0.1.dev93\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-10-06 14:03-0500\n"
"PO-Revision-Date: 2015-10-06 14:03-0500\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.0\n"

#: networking_powervm/plugins/ibm/agent/powervm/agent_base.py:336
msgid "Error has been encountered and logged.  The agent will retry again."
msgstr "Произошла ошибка. Сведения о ней занесены в протокол. Агент повторит операцию."

#: networking_powervm/plugins/ibm/agent/powervm/sea_agent.py:111
#, python-format
msgid "Unable to parse URI %s for provision request assessment."
msgstr "Не удалось проанализировать URI %s для оценки запроса на выделение ресурсов."

#: networking_powervm/plugins/ibm/agent/powervm/sea_agent.py:232
msgid "An error occurred while attempting to update the PVID of the virtual NIC."
msgstr "При попытке обновления PVID виртуального NIC произошла ошибка."

#: networking_powervm/plugins/ibm/agent/powervm/sea_agent.py:454
#, python-format
msgid "Cleaning up VLAN %(vlan)s from the system.  It is no longer in use."
msgstr "Удаление VLAN %(vlan)s из системы. Она больше не используется."

#: networking_powervm/plugins/ibm/agent/powervm/sea_agent.py:512
#, python-format
msgid ""
"Unable to determine the Network Bridge (Shared Ethernet Adapter) for "
"physical network %s.  Will be unable to determine appropriate "
"provisioning action."
msgstr ""
"Не удается определить сетевой мост (общий адаптер Ethernet) для "
"физической сети %s. В этом случае выбор правильного действия для "
"предоставления ресурсов будет невозможен."

#: networking_powervm/plugins/ibm/agent/powervm/utils.py:142
msgid ""
"The bridge_mappings for the agent was not specified.  There was exactly "
"one Network Bridge on the system.  Agent is assuming the default network "
"is backed by the single Network Bridge."
msgstr ""
"Не указано значение bridge_mappings для агента. В системе был ровно один "
"сетевой мост. Агент предполагает, что сеть по умолчанию "
"поддерживается одним сетевым мостом."

#: networking_powervm/plugins/ibm/agent/powervm/utils.py:307
msgid "No NetworkBridges detected on the host."
msgstr "На хосте не обнаружено ни одного сетевого моста."

