# Translations template for networking-powervm.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the networking-powervm
# project.
# Automatically generated, 2015.
#
msgid ""
msgstr ""
"Project-Id-Version: networking-powervm 0.0.1.dev93\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-10-06 14:03-0500\n"
"PO-Revision-Date: 2015-10-06 14:03-0500\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.0\n"

#: networking_powervm/plugins/ibm/agent/powervm/agent_base.py:336
msgid "Error has been encountered and logged.  The agent will retry again."
msgstr "Ein Fehler ist aufgetreten und wurde protokolliert. Der Agent versucht es erneut."

#: networking_powervm/plugins/ibm/agent/powervm/sea_agent.py:111
#, python-format
msgid "Unable to parse URI %s for provision request assessment."
msgstr "URI %s für die Beurteilung der Bereitstellungsanforderung konnte nicht analysiert werden."

#: networking_powervm/plugins/ibm/agent/powervm/sea_agent.py:232
msgid "An error occurred while attempting to update the PVID of the virtual NIC."
msgstr "Beim Versuch der Aktualisierung der PVID der virtuellen NIC ist ein Fehler aufgetreten."

#: networking_powervm/plugins/ibm/agent/powervm/sea_agent.py:454
#, python-format
msgid "Cleaning up VLAN %(vlan)s from the system.  It is no longer in use."
msgstr "Bereinigung von VLAN %(vlan)s aus dem System. Es wird nicht mehr verwendet."

#: networking_powervm/plugins/ibm/agent/powervm/sea_agent.py:512
#, python-format
msgid ""
"Unable to determine the Network Bridge (Shared Ethernet Adapter) for "
"physical network %s.  Will be unable to determine appropriate "
"provisioning action."
msgstr ""
"Die Netzbrücke (gemeinsam genutzter Ethernet-Adapter) für "
"das physische Netz %s konnte nicht bestimmt werden. Es ist nicht möglich, die entsprechende "
"Bereitstellungaktion zu bestimmen."

#: networking_powervm/plugins/ibm/agent/powervm/utils.py:142
msgid ""
"The bridge_mappings for the agent was not specified.  There was exactly "
"one Network Bridge on the system.  Agent is assuming the default network "
"is backed by the single Network Bridge."
msgstr ""
"Die bridge_mappings für den Agent wurden nicht angegeben. Es gab genau "
"eine Netzbrücke im System. Der Agent setzt voraus, dass das Standardnetz "
"durch die einzige Netzbrücke gesichert wird."

#: networking_powervm/plugins/ibm/agent/powervm/utils.py:307
msgid "No NetworkBridges detected on the host."
msgstr "Im Host wurden keine Netzbrücken erkannt."

