# Translations template for nova_powervm.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the nova_powervm
# project.
# Automatically generated, 2015.
#
msgid ""
msgstr ""
"Project-Id-Version: nova_powervm 0.0.1.dev394\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-10-06 13:59-0500\n"
"PO-Revision-Date: 2015-10-06 13:59-0500\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.0\n"

#: nova_powervm/virt/powervm/driver.py:386
#: nova_powervm/virt/powervm/driver.py:396
msgid "VM was not found during destroy operation."
msgstr "A VM não foi localizada durante a operação de destruição."

#: nova_powervm/virt/powervm/driver.py:742
#, python-format
msgid ""
"my_ip address (%(my_ip)s) was not found on any of the interfaces: "
"%(ifaces)s"
msgstr ""
"O endereço my_ip (%(my_ip)s) não foi localizado em qualquer uma das interfaces: "
"%(ifaces)s"

#: nova_powervm/virt/powervm/driver.py:1084
msgid "Rolling back live migration."
msgstr "Retrocedendo a migração em tempo real."

#: nova_powervm/virt/powervm/host.py:174
msgid ""
"Host CPU Metrics determined that the total cycles reported was less than "
"the used cycles.  This indicates an issue with the PCM data.  Please "
"investigate the results."
msgstr ""
"As métricas da CPU do host determinaram que os ciclos totais relatados eram menores que "
"os ciclos usados. Isso indica um problema com os dados de PCM."
"Investigue os resultados."

#: nova_powervm/virt/powervm/media.py:299
#, python-format
msgid "Unable to read volume groups for Virtual I/O Server %s"
msgstr "Não é possível ler os grupos de volume para o Virtual I/O Server %s"

#: nova_powervm/virt/powervm/disk/driver.py:168
#, python-format
msgid ""
"Failed to map boot disk %(disk_name)s of instance %(instance_name)s to "
"the management partition from Virtual I/O Server %(vios_name)s: %(exc)s"
msgstr ""
"Falha ao mapear o disco de inicialização %(disk_name)s da instância %(instance_name)s para "
"a partição de gerenciamento do Virtual I/O Server %(vios_name)s:%(exc)s"

#: nova_powervm/virt/powervm/tasks/network.py:104
#, python-format
msgid ""
"Unable to unplug VIF with mac %(mac)s for instance %(inst)s.  The VIF was"
" not found on the instance."
msgstr ""
"Não é possível desconectar VIF com MAC %(mac)s para a instância %(inst)s. O VIF"
"não foi localizado na instância."

#: nova_powervm/virt/powervm/tasks/storage.py:55
#, python-format
msgid "Volume %(vol)s for instance %(inst)s to be disconnected"
msgstr "O volume %(vol)s para a instância %(inst)s a ser desconectado"

#: nova_powervm/virt/powervm/tasks/storage.py:71
#, python-format
msgid ""
"Unable to disconnect volume for %(inst)s during rollback.  Error was: "
"%(error)s"
msgstr ""
"Não é possível desconectar o volume para %(inst)s durante o retrocesso. O erro foi: "
"%(error)s"

#: nova_powervm/virt/powervm/tasks/storage.py:98
#, python-format
msgid "Volume %(vol)s for instance %(inst)s to be re-connected"
msgstr "Volume %(vol)s para instância %(inst)s a ser conectado novamente"

#: nova_powervm/virt/powervm/tasks/storage.py:115
#, python-format
msgid ""
"Unable to re-connect volume for %(inst)s during rollback.  Error was: "
"%(error)s"
msgstr ""
"Não é possível reconectar o volume para %(inst)s durante o retrocesso. O erro foi: "
"%(error)s"

#: nova_powervm/virt/powervm/tasks/storage.py:156
#, python-format
msgid "Image for instance %s to be deleted"
msgstr "Imagem para a instância %s a ser excluída"

#: nova_powervm/virt/powervm/tasks/storage.py:203
#, python-format
msgid "Disk image being disconnected from instance %s"
msgstr "A imagem do disco está sendo desconectada da instância %s"

#: nova_powervm/virt/powervm/tasks/storage.py:274
#, python-format
msgid ""
"Unmapping boot disk %(disk_name)s of instance %(instance_name)s from "
"management partition via Virtual I/O Server %(vios_name)s."
msgstr ""
"Removendo o mapeamento do disco de inicialização %(disk_name)s da instância %(instance_name)s da "
"partição de gerenciamento por meio do Virtual I/O Server %(vios_name)s."

#: nova_powervm/virt/powervm/tasks/storage.py:286
#, python-format
msgid "Removing disk %(disk_path)s from the management partition."
msgstr "Removendo o disco %(disk_path)s da partição de gerenciamento."

#: nova_powervm/virt/powervm/volume/npiv.py:170
#, python-format
msgid ""
"No storage connections found between the Virtual I/O Servers and FC "
"Fabric %(fabric)s. The connection might be removed already."
msgstr ""
"Não há conexões de armazenamento localizadas entre os Virtual I/O Servers e o FC "
"A malha %(fabric)s. A conexão já pode ser removida."

#: nova_powervm/virt/powervm/volume/npiv.py:478
#, python-format
msgid ""
"No storage connections found between the Virtual I/O Servers and FC "
"Fabric %(fabric)s."
msgstr ""
"Não há conexões de armazenamento localizadas entre os Virtual I/O Servers e o FC "
"Malha %(fabric)s."

#: nova_powervm/virt/powervm/volume/npiv.py:564
#, python-format
msgid ""
"No NPIV mappings exist for instance %(inst)s on fabric %(fabric)s.  May "
"not have connected to the fabric yet or fabric configuration was recently"
" modified."
msgstr ""
"Não existem mapeamentos de NPIV para a instância %(inst)s na malha %(fabric)s. Pode "
"não ter conectado à malha ainda ou a configuração da malha foi recentemente"
"modificada."

#: nova_powervm/virt/powervm/volume/vscsi.py:148
#, python-format
msgid ""
"Discovered device %(dev)s for volume %(volume)s on %(vios)s is in use. "
"Error code: %(status)s."
msgstr ""
"Dispositivo descoberto %(dev)s para o volume %(volume)s no %(vios)s está em uso. "
"Código de erro: %(status)s."

#: nova_powervm/virt/powervm/volume/vscsi.py:237
#, python-format
msgid ""
"Disconnect Volume: No mapped device found on Virtual I/O Server %(vios)s "
"for volume %(volume_id)s.  Volume UDID: %(volume_uid)s"
msgstr ""
"Volume de desconexão: nenhum dispositivo mapeado localizado no Virtual I/O Server %(vios)s "
"para o volume %(volume_id)s. UDID do volume: %(volume_uid)s"

#: nova_powervm/virt/powervm/volume/vscsi.py:246
#, python-format
msgid ""
"Disconnect Volume: Failed to find disk on Virtual I/O Server "
"%(vios_name)s for volume %(volume_id)s. Volume UDID: %(volume_uid)s.  "
"Error: %(error)s"
msgstr ""
"Volume de desconexão: falha ao localizar o disco no Virtual I/O Server "
"%(vios_name)s para o volume %(volume_id)s. O UDID do
volume:%(volume_uid)s.  "
"Erro: %(error)s"

#: nova_powervm/virt/powervm/volume/vscsi.py:288
#, python-format
msgid ""
"Disconnect Volume: Failed to disconnect the volume %(volume_id)s on ANY "
"of the Virtual I/O Servers for instance %(inst)s."
msgstr ""
"Volume de desconexão: falha ao desconectar o volume %(volume_id)s em QUALQUER"
"um dos Virtual I/O Servers para a instância %(inst)s."

#: nova_powervm/virt/powervm/volume/vscsi.py:318
#, python-format
msgid ""
"There was an error removing the hdisk %(disk)s from the Virtual I/O "
"Server."
msgstr ""
"Houve um erro ao remover o hdisk %(disk)s do Virtual I/O "
"Server."

