# Translations template for nova_powervm.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the nova_powervm
# project.
# Automatically generated, 2015.
#
msgid ""
msgstr ""
"Project-Id-Version: nova_powervm 0.0.1.dev394\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-10-06 13:59-0500\n"
"PO-Revision-Date: 2015-10-06 13:59-0500\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.0\n"

#: nova_powervm/virt/powervm/driver.py:131
#, python-format
msgid "Expected exactly one host; found %d"
msgstr "Ожидался только один хост; обнаружено: %d"

#: nova_powervm/virt/powervm/driver.py:695
#, python-format
msgid "Plug vif failed because instance %s was not found."
msgstr "Подключение vif не выполнено, поскольку экземпляр %s не найден."

#: nova_powervm/virt/powervm/driver.py:700
msgid "Plug vif failed because of an unexpected error."
msgstr "Подключение vif не выполнено вследствие непредвиденной ошибки."

#: nova_powervm/virt/powervm/driver.py:797
msgid "Cannot reduce disk size."
msgstr "Невозможно уменьшить размер диска."

#: nova_powervm/virt/powervm/exception.py:37
#, python-format
msgid ""
"Unable to locate the volume group %(vol_grp)s to store the virtual "
"optical media within.  Unable to create the media repository."
msgstr ""
"Не удалось найти группу томов %(vol_grp)s для размещения виртуального "
"оптического носителя. Не удалось создать хранилище носителей."

#: nova_powervm/virt/powervm/exception.py:44
#, python-format
msgid "Expected to find exactly one management partition; found %(count)d."
msgstr "Ожидался только один раздел управления; обнаружено %(count)d."

#: nova_powervm/virt/powervm/exception.py:50
#, python-format
msgid ""
"Having scanned SCSI bus %(bus)x on the management partition, disk with "
"UDID %(udid)s failed to appear after %(polls)d polls over %(timeout)d "
"seconds."
msgstr ""
"После сканирования шины SCSI %(bus)x в разделе управления "
"не удалось отобразить диск с UDID %(udid)s после %(polls)d опросов за %(timeout)d "
"с."

#: nova_powervm/virt/powervm/exception.py:57
#, python-format
msgid ""
"Expected to find exactly one disk on the management partition at "
"%(path_pattern)s; found %(count)d."
msgstr ""
"Ожидался только один диск в разделе управления в "
"%(path_pattern)s; обнаружено %(count)d."

#: nova_powervm/virt/powervm/exception.py:63
#, python-format
msgid ""
"Device %(devpath)s is still present on the management partition after "
"attempting to delete it.  Polled %(polls)d times over %(timeout)d "
"seconds."
msgstr ""
"Устройство %(devpath)s осталось в разделе управления после "
"попытки его удаления. Опрос выполнялся %(polls)d раз за %(timeout)d "
"с."

#: nova_powervm/virt/powervm/exception.py:69
#, python-format
msgid ""
"Failed to map boot disk of instance %(instance_name)s to the management "
"partition from any Virtual I/O Server."
msgstr ""
"Не удалось подключить загрузочный диск экземпляра %(instance_name)s к разделу "
"управления любого виртуального сервера ввода-вывода."

#: nova_powervm/virt/powervm/exception.py:75
#, python-format
msgid ""
"Failed to find newly-created mapping of storage element %(stg_name)s from"
" Virtual I/O Server %(vios_name)s to the management partition."
msgstr ""
"Не удалось найти только что созданную связь элемента памяти %(stg_name)s от"
" виртуального сервера ввода-вывода %(vios_name)s к разделу управления."

#: nova_powervm/virt/powervm/exception.py:81
#, python-format
msgid "Unable to locate the volume group '%(vg_name)s' for this operation."
msgstr "Не удалось найти группу томов '%(vg_name)s' для этой операции."

#: nova_powervm/virt/powervm/exception.py:86
#, python-format
msgid "Unable to locate the Cluster '%(clust_name)s' for this operation."
msgstr "Не удалось найти кластер '%(clust_name)s' для этой операции."

#: nova_powervm/virt/powervm/exception.py:91
msgid "Unable to locate any Cluster for this operation."
msgstr "Не удалось найти кластеры для этой операции."

#: nova_powervm/virt/powervm/exception.py:95
#, python-format
msgid ""
"Unexpectedly found %(clust_count)d Clusters matching name "
"'%(clust_name)s'."
msgstr ""
"Неожиданно обнаружено %(clust_count)d кластеров с именем "
"'%(clust_name)s'."

#: nova_powervm/virt/powervm/exception.py:100
#, python-format
msgid ""
"No cluster_name specified.  Refusing to select one of the %(clust_count)d"
" Clusters found."
msgstr ""
"Не указано имя кластера. Выбор одного из %(clust_count)d"
"обнаруженных кластеров отклонен."

#: nova_powervm/virt/powervm/exception.py:105
#, python-format
msgid ""
"Unable to attach storage (id: %(volume_id)s) to virtual machine "
"%(instance_name)s.  %(reason)s"
msgstr ""
"Не удалось подключить хранилище (id: %(volume_id)s) к виртуальной машине "
"%(instance_name)s. Причины: %(reason)s"

#: nova_powervm/virt/powervm/exception.py:110
#, python-format
msgid ""
"Unable to detach volume (id: %(volume_id)s) from virtual machine "
"%(instance_name)s.  %(reason)s"
msgstr ""
"Не удалось отключить том (id: %(volume_id)s) от виртуальной машины "
"%(instance_name)s. Причины: %(reason)s"

#: nova_powervm/virt/powervm/exception.py:115
#, python-format
msgid ""
"Unable to perform pre live migration steps on volume (id: %(volume_id)s) "
"from virtual machine %(instance_name)s."
msgstr ""
"Не удалось выполнить процедуру подготовки к оперативной миграции для тома (id: %(volume_id)s) "
"из виртуальной машины %(instance_name)s."

#: nova_powervm/virt/powervm/live_migration.py:37
#, python-format
msgid "Live migration of instance '%(name)s' failed for reason: %(reason)s"
msgstr "Сбой оперативной миграции экземпляра '%(name)s', причина: %(reason)s"

#: nova_powervm/virt/powervm/live_migration.py:42
#, python-format
msgid ""
"Live migration of instance '%(name)s' failed because the migration state "
"is: %(state)s"
msgstr ""
"Сбой оперативной миграции экземпляра '%(name)s', поскольку миграция находится в следующем "
"состоянии: %(state)s"

#: nova_powervm/virt/powervm/live_migration.py:47
#, python-format
msgid ""
"Live migration of instance '%(name)s' failed because it is not ready. "
"Reason: %(reason)s"
msgstr ""
"Сбой оперативной миграции экземпляра '%(name)s', поскольку подготовка не выполнена. "
"Причина: %(reason)s"

#: nova_powervm/virt/powervm/live_migration.py:52
#, python-format
msgid ""
"Cannot migrate instance '%(name)s' because the memory region size of the "
"source (%(source_mrs)d MB) does not match the memory region size of the "
"target (%(target_mrs)d MB)."
msgstr ""
"Невозможно выполнить миграцию экземпляра '%(name)s', поскольку размер исходной области памяти "
"(%(source_mrs)d МБ) не совпадает с размером целевой области памяти "
"(%(target_mrs)d МБ)."

#: nova_powervm/virt/powervm/live_migration.py:59
#, python-format
msgid ""
"Cannot migrate %(name)s because its processor compatibility mode %(mode)s"
" is not in the list of modes \"%(modes)s\" supported by the target host."
msgstr ""
"Невозможно выполнить миграцию %(name)s, поскольку режим совместимости процессора %(mode)s"
" отсутствует в списке поддерживаемых режимов \"%(modes)s\" целевого хоста."

#: nova_powervm/virt/powervm/live_migration.py:66
#, python-format
msgid ""
"Cannot migrate %(name)s because the host %(host)s only allows %(allowed)s"
" concurrent migrations and %(running)s migrations are currently running."
msgstr ""
"Невозможно выполнить миграцию %(name)s, поскольку хост %(host)s разрешает не более %(allowed)s"
" параллельных операций миграции, а в данный момент выполняется %(running)s миграций."

#: nova_powervm/virt/powervm/live_migration.py:72
#, python-format
msgid ""
"Cannot migrate %(name)s because the volume %(volume)s cannot be attached "
"on the destination host %(host)s."
msgstr ""
"Невозможно выполнить миграцию %(name)s, поскольку том %(volume)s нельзя подключить "
"к целевому хосту %(host)s."

#: nova_powervm/virt/powervm/vm.py:343
#, python-format
msgid "Multiple Shared Processing Pools with name %(pool)s."
msgstr "Несколько общих пулов процессоров с именем %(pool)s."

#: nova_powervm/virt/powervm/vm.py:347
#, python-format
msgid "Unable to find Shared Processing Pool %(pool)s"
msgstr "Не удалось найти общий пул процессоров %(pool)s"

#: nova_powervm/virt/powervm/vm.py:369
#, python-format
msgid ""
"Flavor attribute %(attr)s must be either True or False.  Current value "
"%(val)s is not allowed."
msgstr ""
"Атрибут Flavor %(attr)s должен иметь значение True или False. Текущее значение "
"%(val)s недопустимо."

#: nova_powervm/virt/powervm/tasks/network.py:39
msgid "Virtual interface unplug failed"
msgstr "Сбой отключения виртуального интерфейса"

#: nova_powervm/virt/powervm/volume/vscsi.py:206
#, python-format
msgid ""
"Failed to discover valid hdisk on any Virtual I/O Server for volume "
"%(volume_id)s."
msgstr ""
"Не удалось найти допустимый жесткий диск на серверах виртуального ввода-вывода для тома "
"%(volume_id)s."

