/home/fjd29/Python/hyperspy/doc/api/hyperspy.rst:37: WARNING: autodoc: failed to import module u'hyperspy.api'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/api.py", line 63, in <module>
    from hyperspy import signals
  File "/home/fjd29/Python/hyperspy/hyperspy/signals.py", line 39, in <module>
    from hyperspy._signals.spectrum import Spectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/spectrum.py", line 25, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.rst:45: WARNING: autodoc: failed to import module u'hyperspy.axes'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.rst:53: WARNING: autodoc: failed to import module u'hyperspy.component'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/component.py", line 27, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.rst:61: WARNING: autodoc: failed to import module u'hyperspy.components'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/components.py", line 34, in <module>
    from hyperspy._components.arctan import Arctan
  File "/home/fjd29/Python/hyperspy/hyperspy/_components/arctan.py", line 23, in <module>
    from hyperspy.component import Component
  File "/home/fjd29/Python/hyperspy/hyperspy/component.py", line 27, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.rst:69: WARNING: autodoc: failed to import module u'hyperspy.decorators'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/decorators.py", line 21, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.rst:77: WARNING: autodoc: failed to import module u'hyperspy.defaults_parser'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.rst:93: WARNING: autodoc: failed to import module u'hyperspy.hspy'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/hspy.py", line 10, in <module>
    from hyperspy import components
  File "/home/fjd29/Python/hyperspy/hyperspy/components.py", line 34, in <module>
    from hyperspy._components.arctan import Arctan
  File "/home/fjd29/Python/hyperspy/hyperspy/_components/arctan.py", line 23, in <module>
    from hyperspy.component import Component
  File "/home/fjd29/Python/hyperspy/hyperspy/component.py", line 27, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.rst:101: WARNING: autodoc: failed to import module u'hyperspy.io'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/io.py", line 23, in <module>
    import hyperspy.defaults_parser
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.rst:117: WARNING: autodoc: failed to import module u'hyperspy.model'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/model.py", line 37, in <module>
    import hyperspy.drawing.spectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/drawing/spectrum.py", line 26, in <module>
    from hyperspy.drawing import utils
  File "/home/fjd29/Python/hyperspy/hyperspy/drawing/utils.py", line 33, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.rst:125: WARNING: autodoc: failed to import module u'hyperspy.signal'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.rst:133: WARNING: autodoc: failed to import module u'hyperspy.signals'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/signals.py", line 39, in <module>
    from hyperspy._signals.spectrum import Spectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/spectrum.py", line 25, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.rst:142: WARNING: missing attribute mentioned in :members: or __all__: module hyperspy, attribute api
/home/fjd29/Python/hyperspy/doc/api/hyperspy._components.rst:10: WARNING: autodoc: failed to import module u'hyperspy._components.arctan'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/_components/arctan.py", line 23, in <module>
    from hyperspy.component import Component
  File "/home/fjd29/Python/hyperspy/hyperspy/component.py", line 27, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy._components.rst:18: WARNING: autodoc: failed to import module u'hyperspy._components.bleasdale'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/_components/bleasdale.py", line 21, in <module>
    from hyperspy.component import Component, Parameter
  File "/home/fjd29/Python/hyperspy/hyperspy/component.py", line 27, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy._components.rst:26: WARNING: autodoc: failed to import module u'hyperspy._components.eels_cl_edge'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/_components/eels_cl_edge.py", line 25, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy._components.rst:34: WARNING: autodoc: failed to import module u'hyperspy._components.eels_double_offset'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/_components/eels_double_offset.py", line 22, in <module>
    from hyperspy.component import Component
  File "/home/fjd29/Python/hyperspy/hyperspy/component.py", line 27, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy._components.rst:42: WARNING: autodoc: failed to import module u'hyperspy._components.eels_double_power_law'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/_components/eels_double_power_law.py", line 21, in <module>
    from hyperspy.component import Component
  File "/home/fjd29/Python/hyperspy/hyperspy/component.py", line 27, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy._components.rst:50: WARNING: autodoc: failed to import module u'hyperspy._components.eels_vignetting'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/_components/eels_vignetting.py", line 20, in <module>
    from hyperspy.component import Component
  File "/home/fjd29/Python/hyperspy/hyperspy/component.py", line 27, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy._components.rst:58: WARNING: autodoc: failed to import module u'hyperspy._components.error_function'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/_components/error_function.py", line 24, in <module>
    from hyperspy.component import Component
  File "/home/fjd29/Python/hyperspy/hyperspy/component.py", line 27, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy._components.rst:66: WARNING: autodoc: failed to import module u'hyperspy._components.exponential'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/_components/exponential.py", line 21, in <module>
    from hyperspy.component import Component
  File "/home/fjd29/Python/hyperspy/hyperspy/component.py", line 27, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy._components.rst:74: WARNING: autodoc: failed to import module u'hyperspy._components.expression'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/_components/expression.py", line 2, in <module>
    from hyperspy.component import Component
  File "/home/fjd29/Python/hyperspy/hyperspy/component.py", line 27, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy._components.rst:82: WARNING: autodoc: failed to import module u'hyperspy._components.gaussian'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/_components/gaussian.py", line 23, in <module>
    from hyperspy.component import Component
  File "/home/fjd29/Python/hyperspy/hyperspy/component.py", line 27, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy._components.rst:90: WARNING: autodoc: failed to import module u'hyperspy._components.logistic'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/_components/logistic.py", line 22, in <module>
    from hyperspy.component import Component
  File "/home/fjd29/Python/hyperspy/hyperspy/component.py", line 27, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy._components.rst:98: WARNING: autodoc: failed to import module u'hyperspy._components.lorentzian'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/_components/lorentzian.py", line 21, in <module>
    from hyperspy.component import Component
  File "/home/fjd29/Python/hyperspy/hyperspy/component.py", line 27, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy._components.rst:106: WARNING: autodoc: failed to import module u'hyperspy._components.offset'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/_components/offset.py", line 22, in <module>
    from hyperspy.component import Component
  File "/home/fjd29/Python/hyperspy/hyperspy/component.py", line 27, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy._components.rst:114: WARNING: autodoc: failed to import module u'hyperspy._components.pes_core_line_shape'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/_components/pes_core_line_shape.py", line 22, in <module>
    from hyperspy.component import Component
  File "/home/fjd29/Python/hyperspy/hyperspy/component.py", line 27, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy._components.rst:122: WARNING: autodoc: failed to import module u'hyperspy._components.pes_see'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/_components/pes_see.py", line 22, in <module>
    from hyperspy.component import Component
  File "/home/fjd29/Python/hyperspy/hyperspy/component.py", line 27, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy._components.rst:130: WARNING: autodoc: failed to import module u'hyperspy._components.polynomial'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/_components/polynomial.py", line 21, in <module>
    from hyperspy.component import Component
  File "/home/fjd29/Python/hyperspy/hyperspy/component.py", line 27, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy._components.rst:138: WARNING: autodoc: failed to import module u'hyperspy._components.power_law'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/_components/power_law.py", line 23, in <module>
    from hyperspy.component import Component
  File "/home/fjd29/Python/hyperspy/hyperspy/component.py", line 27, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy._components.rst:146: WARNING: autodoc: failed to import module u'hyperspy._components.rc'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/_components/rc.py", line 21, in <module>
    from hyperspy.component import Component
  File "/home/fjd29/Python/hyperspy/hyperspy/component.py", line 27, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy._components.rst:154: WARNING: autodoc: failed to import module u'hyperspy._components.scalable_fixed_pattern'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/_components/scalable_fixed_pattern.py", line 20, in <module>
    from hyperspy.component import Component
  File "/home/fjd29/Python/hyperspy/hyperspy/component.py", line 27, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy._components.rst:162: WARNING: autodoc: failed to import module u'hyperspy._components.spline'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/_components/spline.py", line 22, in <module>
    from hyperspy.component import Component
  File "/home/fjd29/Python/hyperspy/hyperspy/component.py", line 27, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy._components.rst:170: WARNING: autodoc: failed to import module u'hyperspy._components.voigt'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/_components/voigt.py", line 22, in <module>
    from hyperspy.component import Component
  File "/home/fjd29/Python/hyperspy/hyperspy/component.py", line 27, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy._components.rst:178: WARNING: autodoc: failed to import module u'hyperspy._components.volume_plasmon_drude'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/_components/volume_plasmon_drude.py", line 21, in <module>
    from hyperspy.component import Component
  File "/home/fjd29/Python/hyperspy/hyperspy/component.py", line 27, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy._signals.rst:10: WARNING: autodoc: failed to import module u'hyperspy._signals.dielectric_function'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/dielectric_function.py", line 23, in <module>
    from hyperspy._signals.spectrum import Spectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/spectrum.py", line 25, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy._signals.rst:18: WARNING: autodoc: failed to import module u'hyperspy._signals.eds'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/eds.py", line 25, in <module>
    from hyperspy import utils
  File "/home/fjd29/Python/hyperspy/hyperspy/utils/__init__.py", line 21, in <module>
    import hyperspy.utils.material
  File "/home/fjd29/Python/hyperspy/hyperspy/utils/material.py", line 2, in <module>
    from hyperspy.misc.material import weight_to_atomic
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/material.py", line 5, in <module>
    from hyperspy.misc.elements import elements as elements_db
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/elements.py", line 10, in <module>
    from hyperspy.misc import utils
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy._signals.rst:26: WARNING: autodoc: failed to import module u'hyperspy._signals.eds_sem'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/eds_sem.py", line 22, in <module>
    from hyperspy._signals.eds import EDSSpectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/eds.py", line 25, in <module>
    from hyperspy import utils
  File "/home/fjd29/Python/hyperspy/hyperspy/utils/__init__.py", line 21, in <module>
    import hyperspy.utils.material
  File "/home/fjd29/Python/hyperspy/hyperspy/utils/material.py", line 2, in <module>
    from hyperspy.misc.material import weight_to_atomic
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/material.py", line 5, in <module>
    from hyperspy.misc.elements import elements as elements_db
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/elements.py", line 10, in <module>
    from hyperspy.misc import utils
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy._signals.rst:34: WARNING: autodoc: failed to import module u'hyperspy._signals.eds_tem'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/eds_tem.py", line 23, in <module>
    from hyperspy import utils
  File "/home/fjd29/Python/hyperspy/hyperspy/utils/__init__.py", line 21, in <module>
    import hyperspy.utils.material
  File "/home/fjd29/Python/hyperspy/hyperspy/utils/material.py", line 2, in <module>
    from hyperspy.misc.material import weight_to_atomic
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/material.py", line 5, in <module>
    from hyperspy.misc.elements import elements as elements_db
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/elements.py", line 10, in <module>
    from hyperspy.misc import utils
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy._signals.rst:42: WARNING: autodoc: failed to import module u'hyperspy._signals.eels'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/eels.py", line 26, in <module>
    from hyperspy._signals.spectrum import Spectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/spectrum.py", line 25, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy._signals.rst:50: WARNING: autodoc: failed to import module u'hyperspy._signals.eels_spectrum_simulation'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/eels_spectrum_simulation.py", line 20, in <module>
    from hyperspy._signals.eels import EELSSpectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/eels.py", line 26, in <module>
    from hyperspy._signals.spectrum import Spectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/spectrum.py", line 25, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy._signals.rst:58: WARNING: autodoc: failed to import module u'hyperspy._signals.image'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/image.py", line 20, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy._signals.rst:66: WARNING: autodoc: failed to import module u'hyperspy._signals.image_simulation'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/image_simulation.py", line 20, in <module>
    from hyperspy._signals.image import Image
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/image.py", line 20, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy._signals.rst:82: WARNING: autodoc: failed to import module u'hyperspy._signals.simulation'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/simulation.py", line 21, in <module>
    from hyperspy.decorators import auto_replot
  File "/home/fjd29/Python/hyperspy/hyperspy/decorators.py", line 21, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy._signals.rst:90: WARNING: autodoc: failed to import module u'hyperspy._signals.spectrum'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/spectrum.py", line 25, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy._signals.rst:98: WARNING: autodoc: failed to import module u'hyperspy._signals.spectrum_simulation'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/spectrum_simulation.py", line 20, in <module>
    from hyperspy._signals.spectrum import Spectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/spectrum.py", line 25, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.drawing.rst:25: WARNING: autodoc: failed to import module u'hyperspy.drawing.image'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/drawing/image.py", line 28, in <module>
    from hyperspy.drawing import widgets
  File "/home/fjd29/Python/hyperspy/hyperspy/drawing/widgets.py", line 27, in <module>
    from .utils import on_figure_window_close
  File "/home/fjd29/Python/hyperspy/hyperspy/drawing/utils.py", line 33, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.drawing.rst:41: WARNING: autodoc: failed to import module u'hyperspy.drawing.mpl_he'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/drawing/mpl_he.py", line 20, in <module>
    from hyperspy.drawing import widgets, spectrum, image
  File "/home/fjd29/Python/hyperspy/hyperspy/drawing/widgets.py", line 27, in <module>
    from .utils import on_figure_window_close
  File "/home/fjd29/Python/hyperspy/hyperspy/drawing/utils.py", line 33, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.drawing.rst:49: WARNING: autodoc: failed to import module u'hyperspy.drawing.mpl_hie'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/drawing/mpl_hie.py", line 19, in <module>
    from hyperspy.drawing import image, utils
  File "/home/fjd29/Python/hyperspy/hyperspy/drawing/image.py", line 28, in <module>
    from hyperspy.drawing import widgets
  File "/home/fjd29/Python/hyperspy/hyperspy/drawing/widgets.py", line 27, in <module>
    from .utils import on_figure_window_close
  File "/home/fjd29/Python/hyperspy/hyperspy/drawing/utils.py", line 33, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.drawing.rst:57: WARNING: autodoc: failed to import module u'hyperspy.drawing.mpl_hse'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/drawing/mpl_hse.py", line 25, in <module>
    from hyperspy.drawing.mpl_he import MPL_HyperExplorer
  File "/home/fjd29/Python/hyperspy/hyperspy/drawing/mpl_he.py", line 20, in <module>
    from hyperspy.drawing import widgets, spectrum, image
  File "/home/fjd29/Python/hyperspy/hyperspy/drawing/widgets.py", line 27, in <module>
    from .utils import on_figure_window_close
  File "/home/fjd29/Python/hyperspy/hyperspy/drawing/utils.py", line 33, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.drawing.rst:73: WARNING: autodoc: failed to import module u'hyperspy.drawing.spectrum'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/drawing/spectrum.py", line 26, in <module>
    from hyperspy.drawing import utils
  File "/home/fjd29/Python/hyperspy/hyperspy/drawing/utils.py", line 33, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.drawing.rst:81: WARNING: autodoc: failed to import module u'hyperspy.drawing.utils'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/drawing/utils.py", line 33, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.drawing.rst:89: WARNING: autodoc: failed to import module u'hyperspy.drawing.widgets'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/drawing/widgets.py", line 27, in <module>
    from .utils import on_figure_window_close
  File "/home/fjd29/Python/hyperspy/hyperspy/drawing/utils.py", line 33, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.external.rst:18: WARNING: autodoc: failed to import module u'hyperspy.external.progressbar'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/external/progressbar.py", line 373
    print('\r', self._format_line(), end=' ')
                                        ^
SyntaxError: invalid syntax
/home/fjd29/Python/hyperspy/doc/api/hyperspy.external.rst:26: WARNING: autodoc: failed to import module u'hyperspy.external.tifffile'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/external/tifffile.py", line 3615
    print("\n%s>\n" % f.lower(), end='')
                                    ^
SyntaxError: invalid syntax
/home/fjd29/Python/hyperspy/hyperspy/external/astroML/bayesian_blocks.py:docstring of hyperspy.external.astroML.bayesian_blocks.FitnessFunc:5: ERROR: Unexpected indentation.
/home/fjd29/Python/hyperspy/hyperspy/external/astroML/bayesian_blocks.py:docstring of hyperspy.external.astroML.bayesian_blocks.FitnessFunc:6: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/fjd29/Python/hyperspy/hyperspy/external/astroML/bayesian_blocks.py:docstring of hyperspy.external.astroML.bayesian_blocks.bayesian_blocks:67: WARNING: Duplicate explicit target name: "1".
/home/fjd29/Python/hyperspy/hyperspy/external/astroML/histtools.py:docstring of hyperspy.external.astroML.histtools.knuth_bin_width:27: WARNING: Duplicate explicit target name: "1".
/home/fjd29/Python/hyperspy/hyperspy/external/astroML/bayesian_blocks.py:docstring of hyperspy.external.astroML.bayesian_blocks:6: ERROR: Duplicate target name, cannot be used as a unique reference: "1".
/home/fjd29/Python/hyperspy/hyperspy/external/astroML/bayesian_blocks.py:docstring of hyperspy.external.astroML.bayesian_blocks.bayesian_blocks:3: ERROR: Duplicate target name, cannot be used as a unique reference: "1".
/home/fjd29/Python/hyperspy/hyperspy/external/astroML/histtools.py:docstring of hyperspy.external.astroML.histtools.knuth_bin_width:1: ERROR: Duplicate target name, cannot be used as a unique reference: "1".
/home/fjd29/Python/hyperspy/hyperspy/external/mpfit/mpfit.py:docstring of hyperspy.external.mpfit.mpfit:4: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/fjd29/Python/hyperspy/hyperspy/external/mpfit/mpfit.py:docstring of hyperspy.external.mpfit.mpfit:9: ERROR: Unexpected indentation.
/home/fjd29/Python/hyperspy/hyperspy/external/mpfit/mpfit.py:docstring of hyperspy.external.mpfit.mpfit:12: ERROR: Unexpected indentation.
/home/fjd29/Python/hyperspy/hyperspy/external/mpfit/mpfit.py:docstring of hyperspy.external.mpfit.mpfit:132: ERROR: Unexpected indentation.
/home/fjd29/Python/hyperspy/hyperspy/external/mpfit/mpfit.py:docstring of hyperspy.external.mpfit.mpfit:142: ERROR: Unexpected indentation.
/home/fjd29/Python/hyperspy/hyperspy/external/mpfit/mpfit.py:docstring of hyperspy.external.mpfit.mpfit:144: ERROR: Unexpected indentation.
/home/fjd29/Python/hyperspy/hyperspy/external/mpfit/mpfit.py:docstring of hyperspy.external.mpfit.mpfit:145: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/fjd29/Python/hyperspy/hyperspy/external/mpfit/mpfit.py:docstring of hyperspy.external.mpfit.mpfit:147: WARNING: Definition list ends without a blank line; unexpected unindent.
/home/fjd29/Python/hyperspy/hyperspy/external/mpfit/mpfit.py:docstring of hyperspy.external.mpfit.mpfit:222: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/fjd29/Python/hyperspy/hyperspy/external/mpfit/mpfit.py:docstring of hyperspy.external.mpfit.mpfit:264: ERROR: Unexpected indentation.
/home/fjd29/Python/hyperspy/hyperspy/external/mpfit/mpfit.py:docstring of hyperspy.external.mpfit.mpfit:265: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/fjd29/Python/hyperspy/hyperspy/external/mpfit/mpfit.py:docstring of hyperspy.external.mpfit.mpfit:284: ERROR: Unexpected indentation.
/home/fjd29/Python/hyperspy/hyperspy/external/mpfit/mpfit.py:docstring of hyperspy.external.mpfit.mpfit:285: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/fjd29/Python/hyperspy/hyperspy/external/mpfit/mpfit.py:docstring of hyperspy.external.mpfit.mpfit:305: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/fjd29/Python/hyperspy/hyperspy/external/mpfit/mpfit.py:docstring of hyperspy.external.mpfit.mpfit:390: ERROR: Unexpected indentation.
/home/fjd29/Python/hyperspy/hyperspy/external/mpfit/mpfit.py:docstring of hyperspy.external.mpfit.mpfit:391: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/fjd29/Python/hyperspy/hyperspy/external/mpfit/mpfit.py:docstring of hyperspy.external.mpfit.mpfit:399: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/fjd29/Python/hyperspy/hyperspy/external/mpfit/mpfitexpr.py:docstring of hyperspy.external.mpfit.mpfitexpr:0: ERROR: Error in "py:module" directive:
no content permitted.

.. py:module:: hyperspy.external.mpfit.mpfitexpr

    Copyright (C) 2009 Sergey Koposov
/home/fjd29/Python/hyperspy/doc/api/hyperspy.gui.rst:10: WARNING: autodoc: failed to import module u'hyperspy.gui.axes'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/gui/__init__.py", line 22, in <module>
    from hyperspy.defaults_parser import current_toolkit
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.gui.rst:18: WARNING: autodoc: failed to import module u'hyperspy.gui.eds'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/gui/__init__.py", line 22, in <module>
    from hyperspy.defaults_parser import current_toolkit
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.gui.rst:26: WARNING: autodoc: failed to import module u'hyperspy.gui.eels'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/gui/__init__.py", line 22, in <module>
    from hyperspy.defaults_parser import current_toolkit
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.gui.rst:34: WARNING: autodoc: failed to import module u'hyperspy.gui.egerton_quantification'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/gui/__init__.py", line 22, in <module>
    from hyperspy.defaults_parser import current_toolkit
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.gui.rst:42: WARNING: autodoc: failed to import module u'hyperspy.gui.main_window'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/gui/__init__.py", line 22, in <module>
    from hyperspy.defaults_parser import current_toolkit
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.gui.rst:50: WARNING: autodoc: failed to import module u'hyperspy.gui.messages'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/gui/__init__.py", line 22, in <module>
    from hyperspy.defaults_parser import current_toolkit
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.gui.rst:58: WARNING: autodoc: failed to import module u'hyperspy.gui.preferences'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/gui/__init__.py", line 22, in <module>
    from hyperspy.defaults_parser import current_toolkit
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.gui.rst:66: WARNING: autodoc: failed to import module u'hyperspy.gui.tools'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/gui/__init__.py", line 22, in <module>
    from hyperspy.defaults_parser import current_toolkit
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.gui.rst:75: WARNING: autodoc: failed to import module u'hyperspy.gui'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/gui/__init__.py", line 22, in <module>
    from hyperspy.defaults_parser import current_toolkit
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.io_plugins.rst:10: WARNING: autodoc: failed to import module u'hyperspy.io_plugins.digital_micrograph'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.io_plugins.rst:18: WARNING: autodoc: failed to import module u'hyperspy.io_plugins.fei'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.io_plugins.rst:26: WARNING: autodoc: failed to import module u'hyperspy.io_plugins.hdf5'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.io_plugins.rst:34: WARNING: autodoc: failed to import module u'hyperspy.io_plugins.image'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.io_plugins.rst:42: WARNING: autodoc: failed to import module u'hyperspy.io_plugins.mrc'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.io_plugins.rst:50: WARNING: autodoc: failed to import module u'hyperspy.io_plugins.msa'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.io_plugins.rst:58: WARNING: autodoc: failed to import module u'hyperspy.io_plugins.netcdf'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.io_plugins.rst:66: WARNING: autodoc: failed to import module u'hyperspy.io_plugins.ripple'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.io_plugins.rst:74: WARNING: autodoc: failed to import module u'hyperspy.io_plugins.tiff'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.io_plugins.rst:83: WARNING: autodoc: failed to import module u'hyperspy.io_plugins'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.learn.rst:18: WARNING: autodoc: failed to import module u'hyperspy.learn.mva'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/learn/mva.py", line 37, in <module>
    from hyperspy.decorators import do_not_replot
  File "/home/fjd29/Python/hyperspy/hyperspy/decorators.py", line 21, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.misc.rst:36: WARNING: autodoc: failed to import module u'hyperspy.misc.elements'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/elements.py", line 10, in <module>
    from hyperspy.misc import utils
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.misc.rst:60: WARNING: autodoc: failed to import module u'hyperspy.misc.hyperspy_magics'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/hyperspy_magics.py", line 5, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.misc.rst:84: WARNING: autodoc: failed to import module u'hyperspy.misc.material'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/material.py", line 5, in <module>
    from hyperspy.misc.elements import elements as elements_db
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/elements.py", line 10, in <module>
    from hyperspy.misc import utils
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.misc.rst:148: WARNING: autodoc: failed to import module u'hyperspy.misc.utils'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.misc.eds.rst:10: WARNING: autodoc: failed to import module u'hyperspy.misc.eds.utils'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/eds/utils.py", line 6, in <module>
    from hyperspy.misc.elements import elements as elements_db
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/elements.py", line 10, in <module>
    from hyperspy.misc import utils
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.misc.eels.rst:10: WARNING: autodoc: failed to import module u'hyperspy.misc.eels.base_gos'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/eels/base_gos.py", line 6, in <module>
    from hyperspy.misc.elements import elements
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/elements.py", line 10, in <module>
    from hyperspy.misc import utils
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.misc.eels.rst:26: WARNING: autodoc: failed to import module u'hyperspy.misc.eels.hartree_slater_gos'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/eels/hartree_slater_gos.py", line 8, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.misc.eels.rst:34: WARNING: autodoc: failed to import module u'hyperspy.misc.eels.hydrogenic_gos'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/eels/hydrogenic_gos.py", line 8, in <module>
    from hyperspy.misc.eels.base_gos import GOSBase
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/eels/base_gos.py", line 6, in <module>
    from hyperspy.misc.elements import elements
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/elements.py", line 10, in <module>
    from hyperspy.misc import utils
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.misc.eels.rst:42: WARNING: autodoc: failed to import module u'hyperspy.misc.eels.tools'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/eels/tools.py", line 9, in <module>
    from hyperspy.gui import messages as messagesui
  File "/home/fjd29/Python/hyperspy/hyperspy/gui/__init__.py", line 22, in <module>
    from hyperspy.defaults_parser import current_toolkit
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.models.rst:10: WARNING: autodoc: failed to import module u'hyperspy.models.eelsmodel'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/models/eelsmodel.py", line 22, in <module>
    from hyperspy.model import Model
  File "/home/fjd29/Python/hyperspy/hyperspy/model.py", line 37, in <module>
    import hyperspy.drawing.spectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/drawing/spectrum.py", line 26, in <module>
    from hyperspy.drawing import utils
  File "/home/fjd29/Python/hyperspy/hyperspy/drawing/utils.py", line 33, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.rst:25: WARNING: autodoc: failed to import module u'hyperspy.tests.test_dictionary_tree_browser'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/test_dictionary_tree_browser.py", line 4, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.axes.rst:10: WARNING: autodoc: failed to import module u'hyperspy.tests.axes.test_data_axis'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/axes/test_data_axis.py", line 7, in <module>
    from hyperspy.axes import DataAxis
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.component.rst:10: WARNING: autodoc: failed to import module u'hyperspy.tests.component.test_component_active_array'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/component/test_component_active_array.py", line 21, in <module>
    from hyperspy.components import Gaussian
  File "/home/fjd29/Python/hyperspy/hyperspy/components.py", line 34, in <module>
    from hyperspy._components.arctan import Arctan
  File "/home/fjd29/Python/hyperspy/hyperspy/_components/arctan.py", line 23, in <module>
    from hyperspy.component import Component
  File "/home/fjd29/Python/hyperspy/hyperspy/component.py", line 27, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.component.rst:18: WARNING: autodoc: failed to import module u'hyperspy.tests.component.test_component_set_parameters'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/component/test_component_set_parameters.py", line 20, in <module>
    from hyperspy.components import Gaussian
  File "/home/fjd29/Python/hyperspy/hyperspy/components.py", line 34, in <module>
    from hyperspy._components.arctan import Arctan
  File "/home/fjd29/Python/hyperspy/hyperspy/_components/arctan.py", line 23, in <module>
    from hyperspy.component import Component
  File "/home/fjd29/Python/hyperspy/hyperspy/component.py", line 27, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.drawing.rst:18: WARNING: autodoc: failed to import module u'hyperspy.tests.drawing.test_marker'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/drawing/test_marker.py", line 22, in <module>
    from hyperspy.signals import Image
  File "/home/fjd29/Python/hyperspy/hyperspy/signals.py", line 39, in <module>
    from hyperspy._signals.spectrum import Spectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/spectrum.py", line 25, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.io.rst:18: WARNING: autodoc: failed to import module u'hyperspy.tests.io.test_dm3'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/io/test_dm3.py", line 26, in <module>
    from hyperspy.io import load
  File "/home/fjd29/Python/hyperspy/hyperspy/io.py", line 23, in <module>
    import hyperspy.defaults_parser
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.io.rst:26: WARNING: autodoc: failed to import module u'hyperspy.tests.io.test_dm4'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/io/test_dm4.py", line 26, in <module>
    from hyperspy.io import load
  File "/home/fjd29/Python/hyperspy/hyperspy/io.py", line 23, in <module>
    import hyperspy.defaults_parser
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.io.rst:34: WARNING: autodoc: failed to import module u'hyperspy.tests.io.test_dm_stackbuilder_plugin'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/io/test_dm_stackbuilder_plugin.py", line 23, in <module>
    from hyperspy.io import load
  File "/home/fjd29/Python/hyperspy/hyperspy/io.py", line 23, in <module>
    import hyperspy.defaults_parser
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.io.rst:42: WARNING: autodoc: failed to import module u'hyperspy.tests.io.test_fei'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/io/test_fei.py", line 24, in <module>
    from hyperspy.io import load
  File "/home/fjd29/Python/hyperspy/hyperspy/io.py", line 23, in <module>
    import hyperspy.defaults_parser
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.io.rst:50: WARNING: autodoc: failed to import module u'hyperspy.tests.io.test_hdf5'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/io/test_hdf5.py", line 8, in <module>
    from hyperspy.io import load
  File "/home/fjd29/Python/hyperspy/hyperspy/io.py", line 23, in <module>
    import hyperspy.defaults_parser
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.io.rst:58: WARNING: autodoc: failed to import module u'hyperspy.tests.io.test_msa'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/io/test_msa.py", line 4, in <module>
    from hyperspy.io import load
  File "/home/fjd29/Python/hyperspy/hyperspy/io.py", line 23, in <module>
    import hyperspy.defaults_parser
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.io.rst:66: WARNING: autodoc: failed to import module u'hyperspy.tests.io.test_tiff'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/io/test_tiff.py", line 6, in <module>
    import hyperspy.api as hs
  File "/home/fjd29/Python/hyperspy/hyperspy/api.py", line 63, in <module>
    from hyperspy import signals
  File "/home/fjd29/Python/hyperspy/hyperspy/signals.py", line 39, in <module>
    from hyperspy._signals.spectrum import Spectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/spectrum.py", line 25, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.model.rst:10: WARNING: autodoc: failed to import module u'hyperspy.tests.model.test_chi_squared'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/model/test_chi_squared.py", line 22, in <module>
    from hyperspy._signals.spectrum import Spectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/spectrum.py", line 25, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.model.rst:18: WARNING: autodoc: failed to import module u'hyperspy.tests.model.test_component'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/model/test_component.py", line 3, in <module>
    from hyperspy.component import Component
  File "/home/fjd29/Python/hyperspy/hyperspy/component.py", line 27, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.model.rst:26: WARNING: autodoc: failed to import module u'hyperspy.tests.model.test_components'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/model/test_components.py", line 4, in <module>
    import hyperspy.api as hs
  File "/home/fjd29/Python/hyperspy/hyperspy/api.py", line 63, in <module>
    from hyperspy import signals
  File "/home/fjd29/Python/hyperspy/hyperspy/signals.py", line 39, in <module>
    from hyperspy._signals.spectrum import Spectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/spectrum.py", line 25, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.model.rst:34: WARNING: autodoc: failed to import module u'hyperspy.tests.model.test_eelsmodel'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/model/test_eelsmodel.py", line 4, in <module>
    import hyperspy.api as hs
  File "/home/fjd29/Python/hyperspy/hyperspy/api.py", line 63, in <module>
    from hyperspy import signals
  File "/home/fjd29/Python/hyperspy/hyperspy/signals.py", line 39, in <module>
    from hyperspy._signals.spectrum import Spectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/spectrum.py", line 25, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.model.rst:42: WARNING: autodoc: failed to import module u'hyperspy.tests.model.test_fit_component'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/model/test_fit_component.py", line 23, in <module>
    from hyperspy._signals.spectrum import Spectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/spectrum.py", line 25, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.model.rst:50: WARNING: autodoc: failed to import module u'hyperspy.tests.model.test_model'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/model/test_model.py", line 4, in <module>
    import hyperspy.api as hs
  File "/home/fjd29/Python/hyperspy/hyperspy/api.py", line 63, in <module>
    from hyperspy import signals
  File "/home/fjd29/Python/hyperspy/hyperspy/signals.py", line 39, in <module>
    from hyperspy._signals.spectrum import Spectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/spectrum.py", line 25, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.model.rst:58: WARNING: autodoc: failed to import module u'hyperspy.tests.model.test_parameter'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/model/test_parameter.py", line 24, in <module>
    from hyperspy.component import Parameter
  File "/home/fjd29/Python/hyperspy/hyperspy/component.py", line 27, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.model.rst:66: WARNING: autodoc: failed to import module u'hyperspy.tests.model.test_set_parameter_state'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/model/test_set_parameter_state.py", line 22, in <module>
    from hyperspy._signals.spectrum import Spectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/spectrum.py", line 25, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.model.rst:74: WARNING: autodoc: failed to import module u'hyperspy.tests.model.test_set_parameter_value'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/model/test_set_parameter_value.py", line 22, in <module>
    from hyperspy._signals.spectrum import Spectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/spectrum.py", line 25, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.mva.rst:10: WARNING: autodoc: failed to import module u'hyperspy.tests.mva.test_bss'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/mva/test_bss.py", line 5, in <module>
    from hyperspy.signals import Spectrum, Image
  File "/home/fjd29/Python/hyperspy/hyperspy/signals.py", line 39, in <module>
    from hyperspy._signals.spectrum import Spectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/spectrum.py", line 25, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.mva.rst:18: WARNING: autodoc: failed to import module u'hyperspy.tests.mva.test_decomposition'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/mva/test_decomposition.py", line 5, in <module>
    from hyperspy import signals
  File "/home/fjd29/Python/hyperspy/hyperspy/signals.py", line 39, in <module>
    from hyperspy._signals.spectrum import Spectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/spectrum.py", line 25, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.mva.rst:26: WARNING: autodoc: failed to import module u'hyperspy.tests.mva.test_export'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/mva/test_export.py", line 4, in <module>
    from hyperspy import signals
  File "/home/fjd29/Python/hyperspy/hyperspy/signals.py", line 39, in <module>
    from hyperspy._signals.spectrum import Spectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/spectrum.py", line 25, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.signal.rst:10: WARNING: autodoc: failed to import module u'hyperspy.tests.signal.test_1D_tools'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/signal/test_1D_tools.py", line 30, in <module>
    import hyperspy.api as hs
  File "/home/fjd29/Python/hyperspy/hyperspy/api.py", line 63, in <module>
    from hyperspy import signals
  File "/home/fjd29/Python/hyperspy/hyperspy/signals.py", line 39, in <module>
    from hyperspy._signals.spectrum import Spectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/spectrum.py", line 25, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.signal.rst:18: WARNING: autodoc: failed to import module u'hyperspy.tests.signal.test_2D_tools'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/signal/test_2D_tools.py", line 23, in <module>
    import hyperspy.api as hs
  File "/home/fjd29/Python/hyperspy/hyperspy/api.py", line 63, in <module>
    from hyperspy import signals
  File "/home/fjd29/Python/hyperspy/hyperspy/signals.py", line 39, in <module>
    from hyperspy._signals.spectrum import Spectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/spectrum.py", line 25, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.signal.rst:26: WARNING: autodoc: failed to import module u'hyperspy.tests.signal.test_apply_function'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/signal/test_apply_function.py", line 5, in <module>
    import hyperspy.api as hs
  File "/home/fjd29/Python/hyperspy/hyperspy/api.py", line 63, in <module>
    from hyperspy import signals
  File "/home/fjd29/Python/hyperspy/hyperspy/signals.py", line 39, in <module>
    from hyperspy._signals.spectrum import Spectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/spectrum.py", line 25, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.signal.rst:34: WARNING: autodoc: failed to import module u'hyperspy.tests.signal.test_assign_subclass'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/signal/test_assign_subclass.py", line 3, in <module>
    import hyperspy.api as hs
  File "/home/fjd29/Python/hyperspy/hyperspy/api.py", line 63, in <module>
    from hyperspy import signals
  File "/home/fjd29/Python/hyperspy/hyperspy/signals.py", line 39, in <module>
    from hyperspy._signals.spectrum import Spectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/spectrum.py", line 25, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.signal.rst:42: WARNING: autodoc: failed to import module u'hyperspy.tests.signal.test_attributes'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/signal/test_attributes.py", line 4, in <module>
    import hyperspy.signals
  File "/home/fjd29/Python/hyperspy/hyperspy/signals.py", line 39, in <module>
    from hyperspy._signals.spectrum import Spectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/spectrum.py", line 25, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.signal.rst:50: WARNING: autodoc: failed to import module u'hyperspy.tests.signal.test_binned'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/signal/test_binned.py", line 4, in <module>
    import hyperspy.api as hs
  File "/home/fjd29/Python/hyperspy/hyperspy/api.py", line 63, in <module>
    from hyperspy import signals
  File "/home/fjd29/Python/hyperspy/hyperspy/signals.py", line 39, in <module>
    from hyperspy._signals.spectrum import Spectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/spectrum.py", line 25, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.signal.rst:58: WARNING: autodoc: failed to import module u'hyperspy.tests.signal.test_eds_sem'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/signal/test_eds_sem.py", line 22, in <module>
    from hyperspy.signals import EDSSEMSpectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/signals.py", line 39, in <module>
    from hyperspy._signals.spectrum import Spectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/spectrum.py", line 25, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.signal.rst:66: WARNING: autodoc: failed to import module u'hyperspy.tests.signal.test_eds_tem'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/signal/test_eds_tem.py", line 22, in <module>
    from hyperspy.signals import EDSTEMSpectrum, Simulation
  File "/home/fjd29/Python/hyperspy/hyperspy/signals.py", line 39, in <module>
    from hyperspy._signals.spectrum import Spectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/spectrum.py", line 25, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.signal.rst:74: WARNING: autodoc: failed to import module u'hyperspy.tests.signal.test_eels'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/signal/test_eels.py", line 22, in <module>
    import hyperspy.api as hs
  File "/home/fjd29/Python/hyperspy/hyperspy/api.py", line 63, in <module>
    from hyperspy import signals
  File "/home/fjd29/Python/hyperspy/hyperspy/signals.py", line 39, in <module>
    from hyperspy._signals.spectrum import Spectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/spectrum.py", line 25, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.signal.rst:82: WARNING: autodoc: failed to import module u'hyperspy.tests.signal.test_fancy_indexing'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/signal/test_fancy_indexing.py", line 25, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.signal.rst:90: WARNING: autodoc: failed to import module u'hyperspy.tests.signal.test_find_peaks1D_ohaver'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/signal/test_find_peaks1D_ohaver.py", line 3, in <module>
    from hyperspy.api import load
  File "/home/fjd29/Python/hyperspy/hyperspy/api.py", line 63, in <module>
    from hyperspy import signals
  File "/home/fjd29/Python/hyperspy/hyperspy/signals.py", line 39, in <module>
    from hyperspy._signals.spectrum import Spectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/spectrum.py", line 25, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.signal.rst:98: WARNING: autodoc: failed to import module u'hyperspy.tests.signal.test_folding'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/signal/test_folding.py", line 4, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.signal.rst:106: WARNING: autodoc: failed to import module u'hyperspy.tests.signal.test_image'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/signal/test_image.py", line 4, in <module>
    from hyperspy.signals import Spectrum, Image
  File "/home/fjd29/Python/hyperspy/hyperspy/signals.py", line 39, in <module>
    from hyperspy._signals.spectrum import Spectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/spectrum.py", line 25, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.signal.rst:114: WARNING: autodoc: failed to import module u'hyperspy.tests.signal.test_integrate_in_range'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/signal/test_integrate_in_range.py", line 4, in <module>
    from hyperspy.signals import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signals.py", line 39, in <module>
    from hyperspy._signals.spectrum import Spectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/spectrum.py", line 25, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.signal.rst:122: WARNING: autodoc: failed to import module u'hyperspy.tests.signal.test_kramers_kronig_transform'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/signal/test_kramers_kronig_transform.py", line 22, in <module>
    from hyperspy.components import VolumePlasmonDrude, Lorentzian
  File "/home/fjd29/Python/hyperspy/hyperspy/components.py", line 34, in <module>
    from hyperspy._components.arctan import Arctan
  File "/home/fjd29/Python/hyperspy/hyperspy/_components/arctan.py", line 23, in <module>
    from hyperspy.component import Component
  File "/home/fjd29/Python/hyperspy/hyperspy/component.py", line 27, in <module>
    from hyperspy.defaults_parser import preferences
  File "/home/fjd29/Python/hyperspy/hyperspy/defaults_parser.py", line 28, in <module>
    from hyperspy.io_plugins import default_write_ext
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/__init__.py", line 21, in <module>
    from hyperspy.io_plugins import (msa, digital_micrograph, fei, mrc,
  File "/home/fjd29/Python/hyperspy/hyperspy/io_plugins/msa.py", line 30, in <module>
    from hyperspy.misc.utils import DictionaryTreeBrowser
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.signal.rst:130: WARNING: autodoc: failed to import module u'hyperspy.tests.signal.test_remove_background'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/signal/test_remove_background.py", line 5, in <module>
    from hyperspy import signals
  File "/home/fjd29/Python/hyperspy/hyperspy/signals.py", line 39, in <module>
    from hyperspy._signals.spectrum import Spectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/spectrum.py", line 25, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.signal.rst:138: WARNING: autodoc: failed to import module u'hyperspy.tests.signal.test_rgb'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/signal/test_rgb.py", line 5, in <module>
    import hyperspy.api as hs
  File "/home/fjd29/Python/hyperspy/hyperspy/api.py", line 63, in <module>
    from hyperspy import signals
  File "/home/fjd29/Python/hyperspy/hyperspy/signals.py", line 39, in <module>
    from hyperspy._signals.spectrum import Spectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/spectrum.py", line 25, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.signal.rst:146: WARNING: autodoc: failed to import module u'hyperspy.tests.signal.test_signal_operators'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/signal/test_signal_operators.py", line 23, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.signal.rst:154: WARNING: autodoc: failed to import module u'hyperspy.tests.signal.test_signal_subclass_conversion'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/signal/test_signal_subclass_conversion.py", line 4, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.signal.rst:162: WARNING: autodoc: failed to import module u'hyperspy.tests.signal.test_spectrum'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/signal/test_spectrum.py", line 4, in <module>
    from hyperspy.signals import Spectrum, Image
  File "/home/fjd29/Python/hyperspy/hyperspy/signals.py", line 39, in <module>
    from hyperspy._signals.spectrum import Spectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/spectrum.py", line 25, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.signal.rst:170: WARNING: autodoc: failed to import module u'hyperspy.tests.signal.test_tools'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/signal/test_tools.py", line 4, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.utils.rst:10: WARNING: autodoc: failed to import module u'hyperspy.tests.utils.test_attrsetter'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/utils/test_attrsetter.py", line 22, in <module>
    from hyperspy.misc.utils import attrsetter
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.utils.rst:18: WARNING: autodoc: failed to import module u'hyperspy.tests.utils.test_material'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/utils/test_material.py", line 6, in <module>
    import hyperspy.api as hs
  File "/home/fjd29/Python/hyperspy/hyperspy/api.py", line 63, in <module>
    from hyperspy import signals
  File "/home/fjd29/Python/hyperspy/hyperspy/signals.py", line 39, in <module>
    from hyperspy._signals.spectrum import Spectrum
  File "/home/fjd29/Python/hyperspy/hyperspy/_signals/spectrum.py", line 25, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.utils.rst:26: WARNING: autodoc: failed to import module u'hyperspy.tests.utils.test_progressbar'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/utils/test_progressbar.py", line 21, in <module>
    from hyperspy.external import progressbar
  File "/home/fjd29/Python/hyperspy/hyperspy/external/progressbar.py", line 373
    print('\r', self._format_line(), end=' ')
                                        ^
SyntaxError: invalid syntax
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.utils.rst:34: WARNING: autodoc: failed to import module u'hyperspy.tests.utils.test_slugify'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/utils/test_slugify.py", line 3, in <module>
    from hyperspy.misc.utils import slugify
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.tests.utils.rst:42: WARNING: autodoc: failed to import module u'hyperspy.tests.utils.test_stack'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/utils/test_stack.py", line 4, in <module>
    from hyperspy.signal import Signal
  File "/home/fjd29/Python/hyperspy/hyperspy/signal.py", line 42, in <module>
    from hyperspy.axes import AxesManager
  File "/home/fjd29/Python/hyperspy/hyperspy/axes.py", line 26, in <module>
    from hyperspy.misc.utils import isiterable, ordinal
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.utils.rst:10: WARNING: autodoc: failed to import module u'hyperspy.utils.eds'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/utils/__init__.py", line 21, in <module>
    import hyperspy.utils.material
  File "/home/fjd29/Python/hyperspy/hyperspy/utils/material.py", line 2, in <module>
    from hyperspy.misc.material import weight_to_atomic
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/material.py", line 5, in <module>
    from hyperspy.misc.elements import elements as elements_db
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/elements.py", line 10, in <module>
    from hyperspy.misc import utils
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.utils.rst:18: WARNING: autodoc: failed to import module u'hyperspy.utils.markers'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/utils/__init__.py", line 21, in <module>
    import hyperspy.utils.material
  File "/home/fjd29/Python/hyperspy/hyperspy/utils/material.py", line 2, in <module>
    from hyperspy.misc.material import weight_to_atomic
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/material.py", line 5, in <module>
    from hyperspy.misc.elements import elements as elements_db
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/elements.py", line 10, in <module>
    from hyperspy.misc import utils
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.utils.rst:26: WARNING: autodoc: failed to import module u'hyperspy.utils.material'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/utils/__init__.py", line 21, in <module>
    import hyperspy.utils.material
  File "/home/fjd29/Python/hyperspy/hyperspy/utils/material.py", line 2, in <module>
    from hyperspy.misc.material import weight_to_atomic
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/material.py", line 5, in <module>
    from hyperspy.misc.elements import elements as elements_db
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/elements.py", line 10, in <module>
    from hyperspy.misc import utils
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.utils.rst:34: WARNING: autodoc: failed to import module u'hyperspy.utils.model'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/utils/__init__.py", line 21, in <module>
    import hyperspy.utils.material
  File "/home/fjd29/Python/hyperspy/hyperspy/utils/material.py", line 2, in <module>
    from hyperspy.misc.material import weight_to_atomic
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/material.py", line 5, in <module>
    from hyperspy.misc.elements import elements as elements_db
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/elements.py", line 10, in <module>
    from hyperspy.misc import utils
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.utils.rst:42: WARNING: autodoc: failed to import module u'hyperspy.utils.plot'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/utils/__init__.py", line 21, in <module>
    import hyperspy.utils.material
  File "/home/fjd29/Python/hyperspy/hyperspy/utils/material.py", line 2, in <module>
    from hyperspy.misc.material import weight_to_atomic
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/material.py", line 5, in <module>
    from hyperspy.misc.elements import elements as elements_db
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/elements.py", line 10, in <module>
    from hyperspy.misc import utils
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/api/hyperspy.utils.rst:51: WARNING: autodoc: failed to import module u'hyperspy.utils'; the following exception was raised:
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/fjd29/Python/hyperspy/hyperspy/utils/__init__.py", line 21, in <module>
    import hyperspy.utils.material
  File "/home/fjd29/Python/hyperspy/hyperspy/utils/material.py", line 2, in <module>
    from hyperspy.misc.material import weight_to_atomic
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/material.py", line 5, in <module>
    from hyperspy.misc.elements import elements as elements_db
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/elements.py", line 10, in <module>
    from hyperspy.misc import utils
  File "/home/fjd29/Python/hyperspy/hyperspy/misc/utils.py", line 24, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
/home/fjd29/Python/hyperspy/doc/citing.rst:None: WARNING: nonlocal image URI found: https://zenodo.org/badge/doi/10.5281/zenodo.46897.svg
/home/fjd29/Python/hyperspy/doc/examples/data_navigation/index.rst:7: ERROR: Unknown directive type "htmlonly".

.. htmlonly::

    :Release: |version|
    :Date: |today|
/home/fjd29/Python/hyperspy/doc/examples/hyperspy_as_library/index.rst:7: ERROR: Unknown directive type "htmlonly".

.. htmlonly::

    :Release: |version|
    :Date: |today|
/home/fjd29/Python/hyperspy/doc/examples/index.rst:7: ERROR: Unknown directive type "htmlonly".

.. htmlonly::

    :Release: |version|
    :Date: |today|
/home/fjd29/Python/hyperspy/doc/examples/index.rst:5: WARNING: duplicate label examples-index, other instance in /home/fjd29/Python/hyperspy/doc/user_guide/examples/index.rst
/home/fjd29/Python/hyperspy/doc/examples/model_fitting/index.rst:7: ERROR: Unknown directive type "htmlonly".

.. htmlonly::

    :Release: |version|
    :Date: |today|
/home/fjd29/Python/hyperspy/doc/examples/simple_simulations/index.rst:7: ERROR: Unknown directive type "htmlonly".

.. htmlonly::

    :Release: |version|
    :Date: |today|
/home/fjd29/Python/hyperspy/doc/index.rst:7: WARNING: Title underline too short.

Welcome to HyperSpy's documentation!
===================================
/home/fjd29/Python/hyperspy/doc/user_guide/eds.rst:4: WARNING: Title underline too short.

Energy-Dispersive X-Rays Spectrometry (EDS)
******************************************
/home/fjd29/Python/hyperspy/doc/user_guide/eels.rst:242: ERROR: Figure caption must be a paragraph or empty comment.

.. figure::  images/curve_fitting_BN.png
   :align:   center
   :width:   500

   Curve fitting quantification of a boron nitride EELS core-loss spectrum from
   `The EELS Data Base
   <http://pc-web.cemes.fr/eelsdb/index.php?page=home.php>`_
/home/fjd29/Python/hyperspy/doc/user_guide/examples/index.rst:7: ERROR: Unknown directive type "htmlonly".

.. htmlonly::

    :Release: |version|
    :Date: |today|
/home/fjd29/Python/hyperspy/doc/user_guide/examples/index.rst:5: WARNING: duplicate label examples-index, other instance in /home/fjd29/Python/hyperspy/doc/examples/index.rst
/home/fjd29/Python/hyperspy/doc/user_guide/getting_started.rst:2: WARNING: Duplicate explicit target name: "ipython".
/home/fjd29/Python/hyperspy/doc/user_guide/getting_started.rst:2: WARNING: Duplicate explicit target name: "ipython".
/home/fjd29/Python/hyperspy/doc/user_guide/index.rst:10: WARNING: toctree contains reference to nonexisting document u'user_guide/credits'
/home/fjd29/Python/hyperspy/doc/user_guide/install.rst:102: ERROR: Unexpected indentation.
/home/fjd29/Python/hyperspy/doc/user_guide/install.rst:2: WARNING: Duplicate explicit target name: "pip".
/home/fjd29/Python/hyperspy/doc/user_guide/io.rst:5: WARNING: Duplicate explicit target name: "open standard format".
/home/fjd29/Python/hyperspy/doc/user_guide/visualisation.rst:176: WARNING: Inline literal start-string without end-string.
../CHANGES.txt:2: WARNING: Duplicate explicit target name: "bugs fixed".
../CHANGES.txt:191: WARNING: Duplicate explicit target name: "changes_0.7.1".
/home/fjd29/Python/hyperspy/doc/api/modules.rst:: WARNING: document isn't included in any toctree
/home/fjd29/Python/hyperspy/doc/examples/index.rst:: WARNING: document isn't included in any toctree
/home/fjd29/Python/hyperspy/doc/user_guide/examples/index.rst:: WARNING: document isn't included in any toctree
/home/fjd29/Python/hyperspy/doc/user_guide/utils.rst:: WARNING: document isn't included in any toctree
/home/fjd29/Python/hyperspy/doc/citing.rst:9: WARNING: Pygments lexer name u'bibtex' is not known
/home/fjd29/Python/hyperspy/doc/examples/data_navigation/1D_image_stack.rst:45: WARNING: undefined label: how-to-search-examples (if the link has no caption the label must precede a section header)
/home/fjd29/Python/hyperspy/doc/examples/data_navigation/2D_image_stack.rst:48: WARNING: undefined label: how-to-search-examples (if the link has no caption the label must precede a section header)
/home/fjd29/Python/hyperspy/doc/examples/data_navigation/line_spectrum.rst:40: WARNING: undefined label: how-to-search-examples (if the link has no caption the label must precede a section header)
/home/fjd29/Python/hyperspy/doc/examples/data_navigation/spectrum_image.rst:45: WARNING: undefined label: how-to-search-examples (if the link has no caption the label must precede a section header)
/home/fjd29/Python/hyperspy/doc/examples/hyperspy_as_library/curve_fitting_data.rst:35: WARNING: undefined label: how-to-search-examples (if the link has no caption the label must precede a section header)
/home/fjd29/Python/hyperspy/doc/examples/hyperspy_as_library/minimal_example.rst:22: WARNING: undefined label: how-to-search-examples (if the link has no caption the label must precede a section header)
/home/fjd29/Python/hyperspy/doc/examples/model_fitting/simple_arctan_fit.rst:42: WARNING: undefined label: how-to-search-examples (if the link has no caption the label must precede a section header)
/home/fjd29/Python/hyperspy/doc/examples/simple_simulations/two_gaussians.rst:73: WARNING: undefined label: how-to-search-examples (if the link has no caption the label must precede a section header)
/home/fjd29/Python/hyperspy/doc/user_guide/eds.rst:363: WARNING: undefined label: visualization_multi_dim (if the link has no caption the label must precede a section header)
/home/fjd29/Python/hyperspy/doc/user_guide/io.rst:230: WARNING: undefined label: hdf5 (if the link has no caption the label must precede a section header)
/home/fjd29/Python/hyperspy/doc/user_guide/model.rst:146: WARNING: undefined label: http://groups.google.com/group/hyperspy-users (if the link has no caption the label must precede a section header)
/home/fjd29/Python/hyperspy/doc/user_guide/visualisation.rst:754: WARNING: undefined label: navigator_options (if the link has no caption the label must precede a section header)
../CHANGES.txt:67: WARNING: undefined label: magic-label (if the link has no caption the label must precede a section header)
../CHANGES.txt:222: WARNING: undefined label: headless-label (if the link has no caption the label must precede a section header)
../CHANGES.txt:257: WARNING: undefined label: inline_plotting (if the link has no caption the label must precede a section header)
WARNING: favicon file 'hyperspy_logo.ico' does not exist
